#!/usr/bin/python3

import configparser
import sys
import getopt
import os
import time

helpMessage = """
Usage:
    GenerateConfig.py

Note: The goal of this script is to generate a good starter configuration for the
Shasta long read assembler. 

Each genome is different and reads differ in quality. So it is impossible to generate a perfect
configuration programmatically. If you'd like to get some suggestions on how to tweak the
configuration generated by this script, you should use the `GetFeedback.py` script after 
you run your assembly.

If you're still not happy with the assembly after using these two scripts, please file a Github
issue and we can help.
"""

def usage():
    print(helpMessage)
    return


def generateConfig(
    genomeSize,
    baseCallerId,
    enableDetangling,
    areUltraLongReads,
):
    minReadLength = 10000
    minAlignedMarkerCount = 400
    if areUltraLongReads:
        minReadLength = 40000
        minAlignedMarkerCount = 600

    config = configparser.ConfigParser()
    config.optionxform = lambda option: option
    config['Reads'] = {
        'minReadLength': str(minReadLength),
        'desiredCoverage': str(genomeSize * 60 * 1000 * 1000), # 60X coverage
        'noCache': 'True',
    }
    config['MinHash'] = {
        'minHashIterationCount': '10',
        'minBucketSize': '0', # Auto select
        'maxBucketSize': '0', # Auto select
        'minFrequency': '5',
    }
    config['Align'] = {
        'alignMethod': '3',
        'downsamplingFactor': '0.05',
        'matchScore': '6',
        'minAlignedFraction': '0.55',
        'minAlignedMarkerCount': str(minAlignedMarkerCount),
        'sameChannelReadAlignment.suppressDeltaThreshold': '30',
    }
    config['MarkerGraph'] = {
        'simplifyMaxLength': '10,100,1000,10000,100000',
        'refineThreshold': '6',
        'crossEdgeCoverageThreshold': '3',
    }
    config['Kmers'] = {
        'k': '14'
    }
    config['Assembly'] = {
        'consensusCaller': 'Bayesian:guppy-3.6.0-a'    
    }

    if baseCallerId == 2:
        # Guppy version less than 3.6.0
        config['Reads']['desiredCoverage'] = str(genomeSize * 80 * 1000 * 1000) # 80X coverage
        config['Kmers']['k'] = '10'
        config['Align']['minAlignedFraction'] = '0.4'
        config['Assembly']['consensusCaller'] = 'Bayesian:guppy-3.0.5-a'
    
    if enableDetangling:
        config['Assembly']['detangleMethod'] = '1'
    
    return config


def main(argv):
    genomeSize = int(input('Approximate genome size in megabasis (Mbp): '))

    baseCallerMessage = """
Which basecaller was used to generate reads?
    Enter 1 for Guppy version >= 3.6.0 (default)
    Enter 2 for Guppy version < 3.6.0 
    """
    print(baseCallerMessage)
    baseCallerIdStr = input('Basecaller : ')
    if baseCallerIdStr == '':
        baseCallerId = 1
    else:
        baseCallerId = int(baseCallerIdStr)
    
    print()

    areUltraLongReads = input('Using Ultra-long reads? [Y/n - default n] : ')
    areUltraLongReads = (areUltraLongReads == 'Y' or areUltraLongReads == 'y')

    enableDetangling = input('Enable detangling? [Y/n - default Y] : ')
    enableDetangling = (enableDetangling == 'Y' or enableDetangling == 'y' or enableDetangling == '')

    config = generateConfig(
        genomeSize,
        baseCallerId,
        enableDetangling,
        areUltraLongReads,
    )

    configFileName = 'generatedShasta.conf'
    with open(configFileName, 'w') as configfile:
        config.write(configfile)

    print("Shasta configuration written out to {}".format(configFileName))
    return


if __name__ == '__main__':
    main(sys.argv[1:])
