// Python-callable test for Edlib library

// Suppress some warning messages generated by Edlib.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"


#include "edlibTest.hpp"

#include "edlib.hpp"
using namespace edlib;

#include "iostream.hpp"
#include "vector.hpp"
using namespace shasta;

void shasta::edlibTest()
{
    const vector<uint32_t> x = {1,2,  4,5,6,7,8};
    const vector<uint32_t> y = {1,2,3,4,5,  7,8};

    EdlibAlignConfig config;
    config.k = -1;
    config.mode = EDLIB_MODE_NW;
    config.task = EDLIB_TASK_PATH;
    config.additionalEqualities = 0;
    config.additionalEqualitiesLength = 0;

    const EdlibAlignResult result = edlibAlign<uint32_t, uint32_t>(
        x.data(), x.size(),
        y.data(), y.size(),
        config);
    if(result.status != EDLIB_STATUS_OK) {
        throw runtime_error("Error during edlibAlign.");
    }
    cout << "Edit distance " << result.editDistance << endl;

    cout << "Alignment:" << endl;
    for(int i=0; i<result.alignmentLength; i++) {
        cout << int(result.alignment[i]);
    }
    cout << endl;

    edlibFreeAlignResult(result);
}

#pragma GCC diagnostic pop
